### ISSUE TITLE
Type check error for map literal

### ISSUE THREAD

**Issue by dram** [cell-lang/compiler#2]
Following code will cause type check error:

```
Main(String* args) {
  d = ["ab" -> "1", "cd" -> "2"];
  k = "a" & "b";
  print d(k, !!);
}
```

Output:

```
Source files parsed
Program is well-formed
Syntax removed
Additional checks passed
Error: the program does not typecheck

File /home/dram/cell/hello.cell lines 1-5
  Line 4: Invalid type: String
    The type must be a subset of <String, String>

Number of functions with typechecking errors: 1
```

**Comment by cell-lang** [comment]
This is not so much a bug, as an intrinsic limitation of the Cell type system. The problem here is that in an expression like the following one:
```
    x = 25;
```
the inferred type for *x* is the singleton type that contains only the value 25:
```
    <25..25>
```
If the typechecker inferred, for example, the type *Int* instead, like most languages do, you would not be able (without an explicit cast) to use *x* as an argument to a function that takes a 32-bit integer, or a byte, or just the number 25.

The same happens with string literals: the type inferred for the string literal *"ab"* is the following one:
```
  <string((<97..97>, <98..98>))>
```
which is, again, the singleton type that contains only the string *"ab"*. These types are totally unreadable of course, so the compiler reports them as *String*, that is, it sacrifices accuracy to improve readability, but that's another source of confusion in this case.

That's also true, to a lesser extent, for set or relation literals. The type inferred for *d* in your code is (more or less) the type of all maps whose keys are the strings *"ab"* or *"cd"* and whose values are the integers *1* or *2*.

The type of *k*, on the other hand, is just *String*, because that's the return type of the *&* operator.

So the compiler rejects the expression *d(k, !!)* (or *d(k)*), because the type of *k* (*String*) is not a subset of the type of the keys of *d* (informally, either of *"ab"* or *"cd"*).

Version 0.3 of the compiler produces a better error message, that explains the problem a bit and suggests explicitly declaring the types of the involved variables (*d* and *k* in this case) in order to fix the problem (that can only be done inside a function though, not inside procedures). 

An alternative would be to relax the typechecking rules a bit and accept the code whenever the type of *k* intersects with the type of the keys of *d*, even if it's not a subset, which is what happens with expressions of the form *d(k, \*)*. That would avoid the problem, but it would also weaken typechecking a bit. It might be worth it, but I haven't made up my mind about this yet.
